# 1 - extraction data from databse for autorizacao, pedido finalizado and procedimento

In [1]:
import sys

# add app to path so we dont get the error ModuleNotFoundError: No module named 'app'
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
from app.services.database.oracle import OracleService
from app.services.database.mariadb import MariaDBService
from app.utils.db_operations import load_query_from_file, execute_query_to_df
from app.utils.config import load_config
from app.utils.logger import get_logger


logger = get_logger(name=__name__)
config_vars = load_config()

In [29]:
# load the query strings
autorizacao_query_file = "/home/joao/projects/company_projects/autorizacoes-api/POC/docs/querys/query_autorizacao.sql"
autorizacao_query_str = load_query_from_file(autorizacao_query_file)

procedimento_query_file = "/home/joao/projects/company_projects/autorizacoes-api/POC/docs/querys/query_procedimento.sql"
procedimento_query_str = load_query_from_file(procedimento_query_file)

finalizado_query_file = "/home/joao/projects/company_projects/autorizacoes-api/POC/docs/querys/query_pedido_finalizado_resposta.sql"
finalizado_query_str = load_query_from_file(finalizado_query_file)

In [30]:
maria_db_procedimento_df = execute_query_to_df(db_service_class=MariaDBService(settings=config_vars), query=procedimento_query_str, fetch_limit=500)
oracle_db_autorizacao_df = execute_query_to_df(db_service_class=OracleService(settings=config_vars), query=autorizacao_query_str)
oracle_db_finalizado_df = execute_query_to_df(db_service_class=OracleService(settings=config_vars), query=finalizado_query_str)

{"timestamp": "2025-08-19T16:17:41", "level": "INFO", "name": "app.services.database.mariadb", "message": "✅ MariaDB connection established to\n                srvawsdb002.cow7tj30bxpl.us-east-1.rds.amazonaws.com:3306/", "filename": "mariadb.py", "lineno": 27}
{"timestamp": "2025-08-19T16:17:41", "level": "INFO", "name": "app.services.database.mariadb", "message": "Executing MariaDB query...", "filename": "mariadb.py", "lineno": 67}
{"timestamp": "2025-08-19T16:17:41", "level": "INFO", "name": "app.services.database.mariadb", "message": "✅ Fetched 280 rows from MariaDB.", "filename": "mariadb.py", "lineno": 75}
{"timestamp": "2025-08-19T16:17:41", "level": "INFO", "name": "app.services.database.mariadb", "message": "✅ MariaDB connection closed.", "filename": "mariadb.py", "lineno": 41}
{"timestamp": "2025-08-19T16:17:41", "level": "INFO", "name": "app.utils.db_operations", "message": "✅ Query executed successfully with 280 sample records", "filename": "db_operations.py", "lineno": 60}
{"timestamp": "2025-08-19T16:17:42", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Connection established to srvhmddb007-otk6s-scan.sbntdb.vcnprod.oraclevcn.com:1521/PRDREPT_OCI", "filename": "oracle.py", "lineno": 33}
{"timestamp": "2025-08-19T16:17:42", "level": "INFO", "name": "app.services.database.oracle", "message": "Executing query...", "filename": "oracle.py", "lineno": 70}
{"timestamp": "2025-08-19T16:17:42", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Fetched 294 rows.", "filename": "oracle.py", "lineno": 91}
{"timestamp": "2025-08-19T16:17:42", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Oracle connection closed.", "filename": "oracle.py", "lineno": 44}
{"timestamp": "2025-08-19T16:17:42", "level": "INFO", "name": "app.utils.db_operations", "message": "✅ Query executed successfully with 294 sample records", "filename": "db_operations.py", "lineno": 60}
{"timestamp": "2025-08-19T16:17:43", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Connection established to srvhmddb007-otk6s-scan.sbntdb.vcnprod.oraclevcn.com:1521/PRDREPT_OCI", "filename": "oracle.py", "lineno": 33}
{"timestamp": "2025-08-19T16:17:43", "level": "INFO", "name": "app.services.database.oracle", "message": "Executing query...", "filename": "oracle.py", "lineno": 70}
{"timestamp": "2025-08-19T16:17:43", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Fetched 118 rows.", "filename": "oracle.py", "lineno": 91}
{"timestamp": "2025-08-19T16:17:43", "level": "INFO", "name": "app.services.database.oracle", "message": "✅ Oracle connection closed.", "filename": "oracle.py", "lineno": 44}
{"timestamp": "2025-08-19T16:17:43", "level": "INFO", "name": "app.utils.db_operations", "message": "✅ Query executed successfully with 118 sample records", "filename": "db_operations.py", "lineno": 60}

In [22]:
maria_db_procedimento_df.head()

,surgical_order_id,procedure,hospitalization_type
0,847154,"[{""code"":31205070,""description"":""CIRURGIA ESTE...",elective
1,848690,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",elective
2,852029,"[{""code"":30205271,""description"":""ADENOIDECTOMI...",elective
3,853333,"[{""code"":31205070,""description"":""CIRURGIA ESTE...",elective
4,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",elective

In [26]:
maria_db_procedimento_df["procedure"].values

array(['[{"code":31205070,"description":"CIRURGIA ESTERILIZADORA MASCULINA","isMain":true,"pro_fat_id":"31205070","procedure_code":31205070,"quantity":1,"surgery_id":6115}]',
       '[{"code":30205050,"description":"AMIGDALECTOMIA DAS PLATINAS","isMain":true,"pro_fat_id":"30205050","procedure_code":30205050,"quantity":1,"surgery_id":1227},{"code":30205069,"description":"AMIDALECTOMIA LINGUAL","isMain":false,"pro_fat_id":"30205069","procedure_code":30205069,"quantity":1,"surgery_id":1236}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30403154,"description":"TIMPANOTOMIA PARA TUBO DE VENTILAÇÃO - UNILATERAL","isMain":false,"pro_fat_id":"30403154","procedure_code":30403154,"quantity":2,"surgery_id":1152},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31205070,"description":"CIRURGIA ESTERILIZADORA MASCULINA","isMain":true,"pro_fat_id":"31205070","procedure_code":31205070,"quantity":1,"surgery_id":6115}]',
       '[{"code":30101557,"description":"EXCISAO E ROT.DE RETALHO(EXTENSOS FERIM.","isMain":true,"pro_fat_id":"30101557","procedure_code":30101557,"quantity":1,"surgery_id":1904}]',
       '[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191},{"code":30403154,"description":"TIMPANOTOMIA PARA TUBO DE VENTILAÇÃO - UNILATERAL","isMain":false,"pro_fat_id":"30403154","procedure_code":30403154,"quantity":2,"surgery_id":1152}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30205050,"description":"AMIGDALECTOMIA DAS PLATINAS","isMain":true,"pro_fat_id":"30205050","procedure_code":30205050,"quantity":1,"surgery_id":1227},{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":false,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30205069,"description":"AMIDALECTOMIA LINGUAL","isMain":false,"pro_fat_id":"30205069","procedure_code":30205069,"quantity":1,"surgery_id":1236},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31403034,"description":"DENERVACAO PERCUTANEA DE FACETA ARTICULAR - POR SEGMENTO","isMain":true,"pro_fat_id":"31403034","procedure_code":31403034,"quantity":5,"surgery_id":866}]',
       '[{"code":30205247,"description":"UVULOPALATO-FARINGOPLASTIA","isMain":true,"pro_fat_id":"30205247","procedure_code":30205247,"quantity":1,"surgery_id":1239},{"code":30205050,"description":"AMIGDALECTOMIA DAS PLATINAS","isMain":false,"pro_fat_id":"30205050","procedure_code":30205050,"quantity":1,"surgery_id":1227},{"code":30205069,"description":"AMIDALECTOMIA LINGUAL","isMain":false,"pro_fat_id":"30205069","procedure_code":30205069,"quantity":1,"surgery_id":1236},{"code":30501369,"description":"SEPTOPLASTIA (QUALQUER TECNICA SEM VIDEO)","isMain":false,"pro_fat_id":"30501369","procedure_code":30501369,"quantity":1,"surgery_id":2006},{"code":30502349,"description":"SINUSOTOMIA ESFENOIDAL POR VIDEOENDOSCOP","isMain":false,"pro_fat_id":"30502349","procedure_code":30502349,"quantity":2,"surgery_id":5931},{"code":30502357,"description":"SINUSOTOMIA FRONTAL INTRANASAL POR VIDEOENDOSCOPIA","isMain":false,"pro_fat_id":"30502357","procedure_code":30502357,"quantity":2,"surgery_id":5969},{"code":30502292,"description":"ANTROSTOMIA MAXILAR INTRANASAL POR VIDEO","isMain":false,"pro_fat_id":"30502292","procedure_code":30502292,"quantity":2,"surgery_id":5968},{"code":30502314,"description":"ETMOIDECTOMIA INTRANASAL POR VIDEOENDOSC","isMain":false,"pro_fat_id":"30502314","procedure_code":30502314,"quantity":2,"surgery_id":5930},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191},{"code":30501067,"description":"CORNETO INFERIOR - CAUTERIZACAO LINEAR, ","isMain":false,"pro_fat_id":"30501067","procedure_code":30501067,"quantity":2,"surgery_id":1197}]',
       '[{"code":40813363,"description":"COLUNA VERTEBRAL: INFILTRACAO FORAMINAL","isMain":true,"pro_fat_id":"40813363","procedure_code":40813363,"quantity":8,"surgery_id":5080},{"code":31602150,"description":"BLOQUEIO NEUROLITICO PERIDURAL OU SUBARACNOIDEO","isMain":false,"pro_fat_id":"31602150","procedure_code":31602150,"quantity":1,"surgery_id":5801},{"code":30713137,"description":"PUNÇÃO ARTICULAR DIAGNÓSTICA OU TERAPÊUT","isMain":false,"pro_fat_id":"30713137","procedure_code":30713137,"quantity":1,"surgery_id":6076}]',
       '[{"code":30101522,"description":"EXTENSOS FERIM-CICATRIZES OU TUMORES EXC","isMain":true,"pro_fat_id":"30101522","procedure_code":30101522,"quantity":3,"surgery_id":604}]',
       '[{"code":30101468,"description":"EXERESE DE LESAO / TUMOR DE PELE E MUCOSAS","isMain":true,"pro_fat_id":"30101468","procedure_code":30101468,"quantity":4,"surgery_id":88}]',
       '[{"code":31602150,"description":"BLOQUEIO NEUROLITICO PERIDURAL OU SUBARACNOIDEO","isMain":true,"pro_fat_id":"31602150","procedure_code":31602150,"quantity":1,"surgery_id":5801},{"code":40813363,"description":"COLUNA VERTEBRAL: INFILTRACAO FORAMINAL","isMain":false,"pro_fat_id":"40813363","procedure_code":40813363,"quantity":5,"surgery_id":5080},{"code":31403026,"description":"BLOQUEIO DE NERVO PERIFERICO","isMain":false,"pro_fat_id":"31403026","procedure_code":31403026,"quantity":5,"surgery_id":4922},{"code":40811026,"description":"RADIOSCOPIA PARA ACOMPANHAMENTO DE PROCEDIMENTO CIRÚRGICO (","isMain":false,"pro_fat_id":"32110022","procedure_code":40811026,"quantity":1,"surgery_id":5511}]',
       '[{"code":31004156,"description":"FISTULECTOMIA ANO-RETAL COM ABAIXAMENTO ","isMain":true,"pro_fat_id":"31004156","procedure_code":31004156,"quantity":1,"surgery_id":2720}]',
       '[{"code":30101522,"description":"EXTENSOS FERIM-CICATRIZES OU TUMORES EXC","isMain":true,"pro_fat_id":"30101522","procedure_code":30101522,"quantity":1,"surgery_id":604},{"code":31403123,"description":"EXPLORACAO CIRURGICA DE NERVO","isMain":false,"pro_fat_id":"31403123","procedure_code":31403123,"quantity":1,"surgery_id":692}]',
       '[{"code":30501350,"description":"RINOSSEPTOPLASTIA","isMain":true,"pro_fat_id":"30501350","procedure_code":30501350,"quantity":1,"surgery_id":1187},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30732115,"description":"TUMOR OSSEO-CURETAGEM OU RESSECCAO COM E","isMain":true,"pro_fat_id":"30732115","procedure_code":30732115,"quantity":1,"surgery_id":1659}]',
       '[{"code":31205070,"description":"CIRURGIA ESTERILIZADORA MASCULINA","isMain":true,"pro_fat_id":"31205070","procedure_code":31205070,"quantity":1,"surgery_id":6115}]',
       '[{"code":31403034,"description":"DENERVACAO PERCUTANEA DE FACETA ARTICULAR - POR SEGMENTO","isMain":true,"pro_fat_id":"31403034","procedure_code":31403034,"quantity":6,"surgery_id":866},{"code":40813363,"description":"COLUNA VERTEBRAL: INFILTRACAO FORAMINAL","isMain":false,"pro_fat_id":"40813363","procedure_code":40813363,"quantity":12,"surgery_id":5080}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30403154,"description":"TIMPANOTOMIA PARA TUBO DE VENTILAÇÃO - UNILATERAL","isMain":false,"pro_fat_id":"30403154","procedure_code":30403154,"quantity":2,"surgery_id":1152},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31003141,"description":"CIRURGIA DE ACESSO POSTERIOR","isMain":true,"pro_fat_id":"31003141","procedure_code":31003141,"quantity":1,"surgery_id":2697},{"code":31004121,"description":"FISTULECTOMIA ANAL EM DOIS TEMPOS","isMain":false,"pro_fat_id":"31004121","procedure_code":31004121,"quantity":1,"surgery_id":199}]',
       '[{"code":30502322,"description":"SINUSECTOMIA MAXILAR - VIA ENDONASAL POR","isMain":true,"pro_fat_id":"30502322","procedure_code":30502322,"quantity":2,"surgery_id":5934},{"code":30502268,"description":"SINUSOTOMIA FRONTAL INTRANASAL","isMain":false,"pro_fat_id":"30502268","procedure_code":30502268,"quantity":2,"surgery_id":1206},{"code":30501369,"description":"SEPTOPLASTIA (QUALQUER TECNICA SEM VIDEO)","isMain":false,"pro_fat_id":"30501369","procedure_code":30501369,"quantity":1,"surgery_id":2006},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191},{"code":30501288,"description":"POLIPECTOMIA - UNILATERAL","isMain":false,"pro_fat_id":"30501288","procedure_code":30501288,"quantity":1,"surgery_id":1185}]',
       '[{"code":30501369,"description":"SEPTOPLASTIA (QUALQUER TECNICA SEM VIDEO)","isMain":true,"pro_fat_id":"30501369","procedure_code":30501369,"quantity":1,"surgery_id":2006},{"code":30502322,"description":"SINUSECTOMIA MAXILAR - VIA ENDONASAL POR","isMain":false,"pro_fat_id":"30502322","procedure_code":30502322,"quantity":2,"surgery_id":5934},{"code":30502349,"description":"SINUSOTOMIA ESFENOIDAL POR VIDEOENDOSCOP","isMain":false,"pro_fat_id":"30502349","procedure_code":30502349,"quantity":1,"surgery_id":5931},{"code":30502357,"description":"SINUSOTOMIA FRONTAL INTRANASAL POR VIDEOENDOSCOPIA","isMain":false,"pro_fat_id":"30502357","procedure_code":30502357,"quantity":1,"surgery_id":5969},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30501350,"description":"RINOSSEPTOPLASTIA","isMain":true,"pro_fat_id":"30501350","procedure_code":30501350,"quantity":1,"surgery_id":1187},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31403220,"description":"MICRO NEUROLISE MULTIPLAS","isMain":true,"pro_fat_id":"31403220","procedure_code":31403220,"quantity":2,"surgery_id":701},{"code":30731097,"description":"TENOLISE NO TUNEL OSTEO FIBROSO","isMain":false,"pro_fat_id":"30731097","procedure_code":30731097,"quantity":2,"surgery_id":688}]',
       '[{"code":30501350,"description":"RINOSSEPTOPLASTIA","isMain":true,"pro_fat_id":"30501350","procedure_code":30501350,"quantity":1,"surgery_id":1187},{"code":30502322,"description":"SINUSECTOMIA MAXILAR - VIA ENDONASAL POR","isMain":false,"pro_fat_id":"30502322","procedure_code":30502322,"quantity":2,"surgery_id":5934},{"code":30502314,"description":"ETMOIDECTOMIA INTRANASAL POR VIDEOENDOSC","isMain":false,"pro_fat_id":"30502314","procedure_code":30502314,"quantity":2,"surgery_id":5930},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30501350,"description":"RINOSSEPTOPLASTIA","isMain":true,"pro_fat_id":"30501350","procedure_code":30501350,"quantity":1,"surgery_id":1187},{"code":30502322,"description":"SINUSECTOMIA MAXILAR - VIA ENDONASAL POR","isMain":false,"pro_fat_id":"30502322","procedure_code":30502322,"quantity":2,"surgery_id":5934},{"code":30502314,"description":"ETMOIDECTOMIA INTRANASAL POR VIDEOENDOSC","isMain":false,"pro_fat_id":"30502314","procedure_code":30502314,"quantity":2,"surgery_id":5930},{"code":30502268,"description":"SINUSOTOMIA FRONTAL INTRANASAL","isMain":false,"pro_fat_id":"30502268","procedure_code":30502268,"quantity":2,"surgery_id":1206},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30101557,"description":"EXTENSOS FERIMENTOS, CICATRIZES OU TUMOR","isMain":true,"pro_fat_id":"30101557","procedure_code":30101557,"quantity":1,"surgery_id":5328}]',
       '[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]',
       '[{"code":30205050,"description":"AMIGDALECTOMIA DAS PLATINAS","isMain":true,"pro_fat_id":"30205050","procedure_code":30205050,"quantity":1,"surgery_id":1227},{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":false,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31203124,"description":"VARICOCELE UNILATERAL-CORRECAO CIRURGICA","isMain":true,"pro_fat_id":"31203124","procedure_code":31203124,"quantity":1,"surgery_id":6445}]',
       '[{"code":30914051,"description":"LINFADENECTOMIA CERVICAL","isMain":true,"pro_fat_id":"30914051","procedure_code":30914051,"quantity":1,"surgery_id":5367},{"code":30805090,"description":"LINFADENECTOMIA MEDIASTINAL","isMain":false,"pro_fat_id":"30805090","procedure_code":30805090,"quantity":1,"surgery_id":5376},{"code":30213053,"description":"TIREOIDECTOMIA TOTAL","isMain":false,"pro_fat_id":"30213053","procedure_code":30213053,"quantity":1,"surgery_id":40}]',
       '[{"code":30713072,"description":"RETIRADA DE ENXERTO OSSEO","isMain":true,"pro_fat_id":"30713072","procedure_code":30713072,"quantity":1,"surgery_id":1689},{"code":30713137,"description":"PUNÇÃO ARTICULAR DIAGNÓSTICA OU TERAPÊUT","isMain":false,"pro_fat_id":"30713137","procedure_code":30713137,"quantity":1,"surgery_id":6076}]',
       '[{"code":30101522,"description":"EXTENSOS FERIM-CICATRIZES OU TUMORES EXC","isMain":true,"pro_fat_id":"30101522","procedure_code":30101522,"quantity":1,"surgery_id":604}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31009166,"description":"HERNIORRAFIA UMBILICAL","isMain":true,"pro_fat_id":"31009166","procedure_code":31009166,"quantity":1,"surgery_id":277}]',
       '[{"code":30301181,"description":"CORRECAO CIRURGICA DE PTOSE PALPEBRAL","isMain":true,"pro_fat_id":"30301181","procedure_code":30301181,"quantity":2,"surgery_id":2018},{"code":30301050,"description":"CANTOPLASTIA LATERAL","isMain":false,"pro_fat_id":"30301050","procedure_code":30301050,"quantity":2,"surgery_id":1054},{"code":30313015,"description":"CIRURGIA DE GLANDULA LACRIMAL","isMain":false,"pro_fat_id":"30313015","procedure_code":30313015,"quantity":2,"surgery_id":1079}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30403154,"description":"TIMPANOTOMIA PARA TUBO DE VENTILAÇÃO - UNILATERAL","isMain":false,"pro_fat_id":"30403154","procedure_code":30403154,"quantity":2,"surgery_id":1152},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":31009158,"description":"HERNIORRAFIA SEM RESSECCAO INTESTINAL -","isMain":true,"pro_fat_id":"31009158","procedure_code":31009158,"quantity":1,"surgery_id":266}]',
       '[{"code":31009166,"description":"HERNIORRAFIA UMBILICAL","isMain":true,"pro_fat_id":"31009166","procedure_code":31009166,"quantity":1,"surgery_id":277}]',
       '[{"code":30602122,"description":"CORREÇÃO DA HIPERTROFIA MAMÁRIA - UNILAT","isMain":true,"pro_fat_id":"30602122","procedure_code":30602122,"quantity":2,"surgery_id":5201}]',
       '[{"code":30101557,"description":"EXTENSOS FERIMENTOS, CICATRIZES OU TUMOR","isMain":true,"pro_fat_id":"30101557","procedure_code":30101557,"quantity":1,"surgery_id":5328}]',
       '[{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":true,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]',
       '[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]',
       '[{"code":30205050,"description":"AMIGDALECTOMIA DAS PLATINAS","isMain":true,"pro_fat_id":"30205050","procedure_code":30205050,"quantity":1,"surgery_id":1227},{"code":30205271,"description":"ADENOIDECTOMIA POR VIDEOENDOSCOPIA","isMain":false,"pro_fat_id":"30205271","procedure_code":30205271,"quantity":1,"surgery_id":5974},{"code":30403154,"description":"TIMPANOTOMIA PARA TUBO DE VENTILAÇÃO - UNILATERAL","isMain":false,"pro_fat_id":"30403154","procedure_code":30403154,"quantity":2,"surgery_id":1152},{"code":30501458,"description":"TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL","isMain":false,"pro_fat_id":"30501458","procedure_code":30501458,"quantity":2,"surgery_id":1191}]',
       '[{"code":30602203,"description":"QUADRANTECTOMIA - RESSECÇÃO SEGMENTAR","isMain":true,"pro_fat_id":"30602203","procedure_code":30602203,"quantity":1,"surgery_id":5199},{"code":30602254,"description":"RECONSTRUCAO PARCIAL DA MAMA POS-QUADRANTECTOMIA","isMain":false,"pro_fat_id":"30602254","procedure_code":30602254,"quantity":1,"surgery_id":2088}]',
       '[{"code":30602076,"description":"EXERESE DE LESAO DA MAMA POR MARCACAO ES","isMain":true,"pro_fat_id":"30602076","procedure_code":30602076,"quantity":2,"surgery_id":451},{"code":30602246,"description":"RECONST. DE MAMA","isMain":false,"pro_fat_id":"30602246","procedure_code":30602246,"quantity":2,"surgery_id":2075}]',
       '[{"code":31403034,"description":"DENERVACAO PERCUTANEA DE FACETA ARTICULAR - POR SEGMENTO","isMain":true,"pro_fat_id":"31403034","procedure_code":31403034,"quantity":8,"surgery_id":866}]',

In [23]:
oracle_db_autorizacao_df.head()

,CD_GUIA,TP_GUIA,CD_AVISO_CIRURGIA,TP_SITUACAO,DT_SOLICITACAO,DT_AUTORIZACAO,CD_AVISO,DT_INSERCAO,DT_OVERMIND,DS_PROTOCOLO,DT_STATUS,TP_STATUS,DS_STATUS,CD_SENHA,DT_SENHA,DS_GUIA_PATH
0,19755750.0,I,867256,C,2025-08-07,NaT,867256.0,2025-08-07 09:16:24,2025-08-07 09:16:30,122283869,2025-08-07 09:16:30,L,None,None,None,None
1,19671649.0,I,864026,A,2025-07-29,2025-07-30 09:16:23,864026.0,2025-07-30 09:03:24,2025-07-30 09:03:31,121937018,2025-07-30 09:18:36,A,None,JMBSQB0,None,https://cdns.overmind.ai/autorizacao-bradesco-...
2,19672750.0,I,864095,S,2025-08-18,NaT,864095.0,2025-07-30 09:03:46,2025-07-30 09:03:46,None,2025-07-30 09:03:46,F,OVM_000101-Login ou Senha do Site da Operadora...,None,None,None
3,19706072.0,I,865360,A,2025-08-01,2025-08-18 10:51:55,865360.0,2025-08-01 14:20:44,2025-08-01 14:20:50,122070452,2025-08-18 10:51:55,A,None,JMK2K49,None,https://cdns.overmind.ai/autorizacao-bradesco-...
4,19673442.0,I,864135,C,2025-07-29,2025-08-13 11:06:22,864135.0,2025-07-30 09:03:28,2025-07-30 09:04:30,122702933,2025-08-13 11:06:22,A,None,88236478,None,https://cdns.overmind.ai/autorizacao-segurosun...

In [32]:
oracle_db_finalizado_df.head()

,CD_REGISTRO_CONTATO,CD_REGISTRO_VINCULADO,DT_CONTATO,HR_CONTATO,CD_USUARIO,DS_ASSUNTO,DS_CONTATO,TP_ACAO,CD_PACIENTE,NM_PACIENTE
0,3772444,857416,2025-07-15 16:36:02,2025-07-15 16:36:02,C05895,PEDIDO FINALIZADO,\n Procedimento Autorizado\n Pacient...,AC,None,SALETE EMILIA DOS SANTOS LIMA
1,3778275,857469,2025-07-17 15:58:58,2025-07-17 15:58:58,C28613,PEDIDO FINALIZADO,\n Procedimento Autorizado\n Pacient...,AC,None,BARBARA ARAUJO SCHNNEPPEL CORREA
2,3790912,861632,2025-07-23 08:15:48,2025-07-23 08:15:48,C20837,PEDIDO FINALIZADO,\n Procedimento Autorizado\n Pacient...,AC,None,LIDIANE CINTIA BATISTA RODRIGUES
3,3792811,858315,2025-07-23 10:56:21,2025-07-23 10:56:21,C27366,PEDIDO FINALIZADO,\n Procedimento Autorizado\n Pacient...,AC,None,TELMA REGINA KELLES RIOS
4,3793934,860565,2025-07-23 16:41:29,2025-07-23 16:41:29,C26329,PEDIDO FINALIZADO,\n Procedimento Autorizado\n Pacient...,AC,None,PEDRO HENRIQUE RODRIGUES MIRANDA

## getting a single table with the info we need

In [35]:
import pandas as pd

maria_db_procedimento_df_processed = maria_db_procedimento_df.rename(columns={"surgical_order_id": "CD_AVISO_CIRURGIA", "procedure": "DS_PROCEDIMENTO"})
maria_db_procedimento_df_processed.drop(columns=["hospitalization_type"], inplace=True)
maria_db_procedimento_df_processed = maria_db_procedimento_df_processed[maria_db_procedimento_df_processed["DS_PROCEDIMENTO"].notna()]
maria_db_procedimento_df_processed.reset_index(drop=True, inplace=True)

autorizacao_no_need_cols = [col for col in oracle_db_autorizacao_df.columns if col not in ["CD_AVISO_CIRURGIA", "CD_GUIA", "CD_SENHA", "DS_GUIA_PATH"]]
oracle_db_autorizacao_df_processed = oracle_db_autorizacao_df.drop(columns=autorizacao_no_need_cols)
oracle_db_autorizacao_df_processed = oracle_db_autorizacao_df_processed[oracle_db_autorizacao_df_processed["DS_GUIA_PATH"].notna()]
oracle_db_autorizacao_df_processed.reset_index(drop=True, inplace=True)

finalizado_no_need_cols = [col for col in oracle_db_finalizado_df.columns if col not in ["CD_REGISTRO_VINCULADO", "DS_CONTATO"]]
oracle_db_finalizado_df_processed = oracle_db_finalizado_df.drop(columns=finalizado_no_need_cols)
oracle_db_finalizado_df_processed.rename(columns={"CD_REGISTRO_VINCULADO": "CD_AVISO_CIRURGIA"}, inplace=True)
oracle_db_finalizado_df_processed = oracle_db_finalizado_df_processed[oracle_db_finalizado_df_processed["DS_CONTATO"].notna()]
oracle_db_finalizado_df_processed.reset_index(drop=True, inplace=True)

In [36]:
print(maria_db_procedimento_df_processed.info())
print(oracle_db_autorizacao_df_processed.info())
print(oracle_db_finalizado_df_processed.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_AVISO_CIRURGIA  280 non-null    int64
 1   DS_PROCEDIMENTO    280 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_GUIA            80 non-null     float64
 1   CD_AVISO_CIRURGIA  80 non-null     int64
 2   CD_SENHA           67 non-null     object
 3   DS_GUIA_PATH       80 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 2.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_AVISO_CIRURGIA  118 non-null    int64
 1   DS_CONTATO         118 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.0+ KB
None

In [37]:
merged_df_autorizacao = pd.merge(
    maria_db_procedimento_df_processed,
    oracle_db_autorizacao_df_processed,
    on="CD_AVISO_CIRURGIA",
    how="inner"
)

In [38]:
merged_df_autorizacao_final = pd.merge(
    merged_df_autorizacao,
    oracle_db_finalizado_df_processed,
    on="CD_AVISO_CIRURGIA",
    how="inner"
)

In [39]:
print(merged_df_autorizacao_final.info())
merged_df_autorizacao_final.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_AVISO_CIRURGIA  60 non-null     int64
 1   DS_PROCEDIMENTO    60 non-null     object
 2   CD_GUIA            60 non-null     float64
 3   CD_SENHA           47 non-null     object
 4   DS_GUIA_PATH       60 non-null     object
 5   DS_CONTATO         60 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.9+ KB
None

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...

In [40]:
# save to sql db
# save merged df
import sqlalchemy

# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///gold_autorizacao_database.sqlite")


# Save the DataFrame to a SQLite table
merged_df_autorizacao_final.to_sql("autorizacao", engine, if_exists="replace", index=False)

# load 
df_merged_final = pd.read_sql("SELECT * FROM autorizacao", engine)

## 1.5 PART

In [41]:
# load into memory
import sqlalchemy
import pandas as pd

# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///gold_autorizacao_database.sqlite")
merged_df_autorizacao_final = pd.read_sql("SELECT * FROM autorizacao", engine)

In [42]:
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...